version: '3.9'

services: 

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3000:80
    restart: always
    volumes:
      - ./api:/var/www/html/
    depends_on:
      - db

  web-app:
    image: node:18.14-alpine
    container_name: web-app
    restart: always
    working_dir: /app
    command: "npm start"
    ports:
      - 3001:3000
    volumes: 
      - ./web-app:/app

  db:
    image: mysql:8.0
    container_name: db_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=contato_seguro
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devadmin
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db