version: '3.9'
services: 

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 81:80
    restart: always
    volumes:
      - ./api:/var/www/html/
    depends_on:
      - db
    networks:
        - my-network

  web-app:
    image: node:19.7.0-alpine3.17
    container_name: web-app
    restart: always
    working_dir: /app
    command: "npm start"
    ports:
      - 3000:3000
    volumes: 
      - ./web-app:/app
    depends_on:
      - api
    networks:
        - my-network

  db:
    image: mysql:8.0
    container_name: db_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=contato_seguro
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devadmin
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    networks:
        - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    networks:
        - my-network

networks:
  my-network:
